# Generated by Django 4.2 on 2024-03-04 20:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_paddle_billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("past_due", "Past Due"),
                    ("paused", "Paused"),
                    ("canceled", "Canceled"),
                ],
                max_length=10,
            ),
        ),
    ]
